using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;

/// <summary>
/// Drop this on an empty GameObject in EndScene. It builds a full-screen background
/// image (your own artwork, with all the congrats/credits text already baked into
/// it) plus a single Main Menu button anchored at the very bottom of the screen.
/// No text is generated by this script anymore — just assign your image below.
/// </summary>
public class EndSceneUI : MonoBehaviour
{
    [Header("Background")]
    [Tooltip("Your background image — already includes the congrats message, credits, etc.")]
    public Sprite backgroundImage;

    [Header("Main Menu Button")]
    [Tooltip("Exact name of the main menu scene, as it appears in Build Settings.")]
    public string mainMenuSceneName = "MainMenu";
    [Tooltip("Leave blank (default) if the button's label is already part of your background image.")]
    public string buttonLabel = "";
    [Tooltip("Set alpha to 0 (default) for a fully invisible, click-only button — " +
             "useful when the button graphic is already baked into your background image.")]
    public Color buttonColor = new Color(1f, 1f, 1f, 0f);

    [Header("Button Position")]
    [Tooltip("How far up from the bottom edge of the screen, in pixels, the button sits.")]
    public float buttonBottomMargin = 60f;
    public float buttonWidth = 320f;
    public float buttonHeight = 80f;

    void Start()
    {
        BuildUI();
    }

    private void BuildUI()
    {
        // UI Buttons need an EventSystem in the scene to receive clicks at all —
        // easy to forget when building UI by hand, so this creates one if the
        // scene doesn't already have one.
        if (FindObjectOfType<EventSystem>() == null)
        {
            new GameObject("EventSystem", typeof(EventSystem), typeof(StandaloneInputModule));
        }

        // --- Canvas ---
        GameObject canvasGO = new GameObject("EndCanvas", typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster));
        Canvas canvas = canvasGO.GetComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;

        CanvasScaler scaler = canvasGO.GetComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);

        // --- Background image, stretched full-screen ---
        GameObject bgGO = new GameObject("Background", typeof(Image));
        bgGO.transform.SetParent(canvasGO.transform, false);
        Image bgImage = bgGO.GetComponent<Image>();
        bgImage.sprite = backgroundImage;
        bgImage.preserveAspect = false; // fills the whole screen exactly, no letterboxing
        RectTransform bgRect = bgGO.GetComponent<RectTransform>();
        bgRect.anchorMin = Vector2.zero;
        bgRect.anchorMax = Vector2.one;
        bgRect.offsetMin = Vector2.zero;
        bgRect.offsetMax = Vector2.zero;

        // --- Main Menu button, anchored to the bottom of the screen ---
        CreateButton(canvasGO.transform, "MainMenuButton", buttonLabel);
    }

    /// <summary>Loads the main menu scene. Wired to the button's OnClick automatically.</summary>
    private void GoToMainMenu()
    {
        SceneManager.LoadScene(mainMenuSceneName);
    }

    /// <summary>Creates a horizontally-centered button anchored to the bottom edge of
    /// the screen, wired to call GoToMainMenu() on click.</summary>
    private void CreateButton(Transform parent, string name, string label)
    {
        GameObject buttonGO = new GameObject(name, typeof(Image), typeof(Button));
        buttonGO.transform.SetParent(parent, false);

        Image buttonImage = buttonGO.GetComponent<Image>();
        buttonImage.color = buttonColor;

        RectTransform rect = buttonGO.GetComponent<RectTransform>();
        // Anchored to the bottom-center of the screen, offset up by buttonBottomMargin.
        rect.anchorMin = new Vector2(0.5f, 0f);
        rect.anchorMax = new Vector2(0.5f, 0f);
        rect.pivot = new Vector2(0.5f, 0f);
        rect.sizeDelta = new Vector2(buttonWidth, buttonHeight);
        rect.anchoredPosition = new Vector2(0f, buttonBottomMargin);

        Button button = buttonGO.GetComponent<Button>();
        button.onClick.AddListener(GoToMainMenu);

        if (string.IsNullOrEmpty(label)) return;

        Font legacyFont = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");

        // Label as a child Text, stretched to fill the button.
        GameObject labelGO = new GameObject("Label", typeof(Text));
        labelGO.transform.SetParent(buttonGO.transform, false);
        Text labelText = labelGO.GetComponent<Text>();
        labelText.text = label;
        labelText.font = legacyFont;
        labelText.fontSize = 28;
        labelText.fontStyle = FontStyle.Bold;
        labelText.alignment = TextAnchor.MiddleCenter;
        labelText.color = Color.white;

        RectTransform labelRect = labelGO.GetComponent<RectTransform>();
        labelRect.anchorMin = Vector2.zero;
        labelRect.anchorMax = Vector2.one;
        labelRect.offsetMin = Vector2.zero;
        labelRect.offsetMax = Vector2.zero;
    }
}